POST  http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "pepito",
  "email": "pepito@gmail.com",
  "password": "12345678",
  "dateBirth": "2000-02-02",
  "rol": "USER"
}

### error
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "juanito@gmail.com",
  "password": "111"
}

### exito
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "juanito@gmail.com",
  "password": "12345678"
}
> {% client.global.set("auth_token", response.body.msg.token); %}

###
PUT http://localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Carlos",
  "phone": "333333",
  "photoUrl": "mi foto",
  "dateBirth": "2000-08-22"
}