### register
POST  http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "carlitos",
  "email": "carlitos@email.com",
  "password": "12345678",
  "dateBirth": "2000-02-02",
  "rol": "USER"
}

### exito login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "juan@email.com",
  "password": "12345678"
}
> {% client.global.set("auth_token", response.body.msg.token); %}

### error login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "juanito@email.com",
  "password": "111"
}

###exito recover
POST http://localhost:8080/api/auth/recover
Content-Type: application/json

{
  "email": "carlitos@email.com"
}

### error recover
POST http://localhost:8080/api/auth/recover
Content-Type: application/json

{
  "email": "carlitosemail.com"
}

###exito reset
POST http://localhost:8080/api/auth/reset
Content-Type: application/json

{
  "email": "carlitos@email.com",
  "code": "1ACM75EB",
  "password": "12345678"
}

###error reset
POST http://localhost:8080/api/auth/reset
Content-Type: application/json

{
  "email": "carlitos@email.com",
  "code": "1ACM75EB",
  "password": "1234"
}
