GET http://localhost:8080/api/accommodations/1/metrics?to=2023-10-10

###exito crear
POST http://localhost:8080/api/reservations
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "accommodationId": 2,
  "dateFrom": "2027-04-04T00:00:00",
  "dateTo": "2027-05-05T00:00:00",
  "guests": 2
}

###error crear
POST http://localhost:8080/api/reservations
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "accommodationId": 2,
  "dateFrom": "2026-06-06T00:00:00",
  "dateTo": "2026-05-05T00:00:00",
  "guests": 2
}

###exito listar
GET  http://localhost:8080/api/reservations?page=0
Authorization: Bearer {{auth_token}}

###exito detalle
GET  http://localhost:8080/api/reservations/2
Authorization: Bearer {{auth_token}}

###exito cancel
PATCH http://localhost:8080/api/reservations/4/status
Authorization: Bearer {{auth_token}}
