### exito editUser
PUT http://localhost:8080/api/users/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Carlos",
  "phone": "333333",
  "photoUrl": "mi foto",
  "dateBirth": "2000-08-22"
}

### error editUser
PUT http://localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Carlos",
  "phone": "333333",
  "photoUrl": "mi foto",
  "dateBirth": "2000-08-22"
}

### deleteUser
DELETE http://localhost:8080/api/users/1
Authorization: Bearer {{auth_token}}

### exito getUser
GET http://localhost:8080/api/users/3
Authorization: Bearer {{auth_token}}

### error getUser
GET http://localhost:8080/api/users/1
Authorization: Bearer {{auth_token}}

### exito changePassword
PUT http://localhost:8080/api/users/3/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "oldPassword": "12345678",
  "newPassword": "24688642"
}

### error changePassword
PUT http://localhost:8080/api/users/3/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "oldPassword": "24688642",
  "newPassword": "12345678"
}
